---
name: CI (master)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  unit_tests:
    name: Unit Tests
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v2.1.0
      - uses: actions/setup-node@v1.4.2
        with:
          node-version: '13'
      - name: Linting
        run: npm run lint
      - name: Testing with coverage
        uses: paambaati/codeclimate-action@v2.6.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: npm test
          debug: true
